export const AuditAction = {
  AuthLogin: 'AUTH_LOGIN',
  UserRoleChanged: 'USER_ROLE_CHANGED',
  UserStatusChanged: 'USER_STATUS_CHANGED',
  CoursePublished: 'COURSE_PUBLISHED',
  AssignmentPublished: 'ASSIGNMENT_PUBLISHED',
  QuizPublished: 'QUIZ_PUBLISHED',
  SubmissionGraded: 'SUBMISSION_GRADED',
  CertificateIssued: 'CERTIFICATE_ISSUED',
  CertificateRevoked: 'CERTIFICATE_REVOKED',
  CommunityPostModerated: 'COMMUNITY_POST_MODERATED',
  CommunityPostRemoved: 'COMMUNITY_POST_REMOVED',
  CommunityCommentRemoved: 'COMMUNITY_COMMENT_REMOVED',
  ContentModerationChanged: 'CONTENT_MODERATION_CHANGED',
  VoucherCreated: 'VOUCHER_CREATED',
  VoucherUpdated: 'VOUCHER_UPDATED',
  VoucherRedeemed: 'VOUCHER_REDEEMED',
  CommerceCartItemAdded: 'COMMERCE_CART_ITEM_ADDED',
  CommerceCartItemRemoved: 'COMMERCE_CART_ITEM_REMOVED',
  CommerceCartCleared: 'COMMERCE_CART_CLEARED',
  CommerceOrderCreated: 'COMMERCE_ORDER_CREATED',
  CommerceCatalogPriceUpdated: 'COMMERCE_CATALOG_PRICE_UPDATED',
  CommerceProductStatusChanged: 'COMMERCE_PRODUCT_STATUS_CHANGED',
  ScholarshipCreated: 'SCHOLARSHIP_CREATED',
  ScholarshipUpdated: 'SCHOLARSHIP_UPDATED',
  ScholarshipApplied: 'SCHOLARSHIP_APPLIED',
  TmiRewardCreated: 'TMI_REWARD_CREATED',
  TmiRewardUpdated: 'TMI_REWARD_UPDATED',
  TmiRewardRedeemed: 'TMI_REWARD_REDEEMED',
  TmiRewardRefunded: 'TMI_REWARD_REFUNDED',
  TmiBalanceAdjusted: 'TMI_BALANCE_ADJUSTED',
  JobCreated: 'JOB_CREATED',
  JobUpdated: 'JOB_UPDATED',
  JobPublished: 'JOB_PUBLISHED',
  JobClosed: 'JOB_CLOSED',
  JobDeleted: 'JOB_DELETED',
  MentorApprovalChanged: 'MENTOR_APPROVAL_CHANGED',
} as const;

export type AuditActionValue = (typeof AuditAction)[keyof typeof AuditAction];
